-- ARES Logistica - gestione utenti protetta e registro amministrativo
--
-- Questa migrazione prepara il database per la Edge Function
-- `ares-admin-users`. Non crea utenti e non invia email da sola.

begin;

create table if not exists public.ares_admin_audit (
    id bigint generated by default as identity primary key,
    actor_user_id uuid references auth.users(id) on delete set null,
    target_user_id uuid references auth.users(id) on delete set null,
    target_email text,
    action text not null
        check (action in ('invite_user', 'activate_user', 'deactivate_user')),
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists ares_admin_audit_created_at_idx
    on public.ares_admin_audit (created_at desc);
create index if not exists ares_admin_audit_actor_idx
    on public.ares_admin_audit (actor_user_id);
create index if not exists ares_admin_audit_target_idx
    on public.ares_admin_audit (target_user_id);

alter table public.ares_admin_audit enable row level security;

-- I profili completi (compresa l'email) sono visibili soltanto al proprietario
-- del profilo e al Super Amministratore. Gli altri ruoli non ricevono l'elenco.
drop policy if exists ares_profiles_select_self_or_staff on public.ares_profiles;
drop policy if exists ares_profiles_select_self_or_super_admin on public.ares_profiles;
create policy ares_profiles_select_self_or_super_admin
on public.ares_profiles for select to authenticated
using (id = auth.uid() or public.current_ares_role() = 'super_admin');

drop policy if exists ares_admin_audit_super_admin_select on public.ares_admin_audit;
create policy ares_admin_audit_super_admin_select
on public.ares_admin_audit for select to authenticated
using (public.current_ares_role() = 'super_admin');

revoke all on public.ares_admin_audit from anon, authenticated;
grant select on public.ares_admin_audit to authenticated;

commit;
